### ISSUE TITLE
copy not working in chrome

### ISSUE THREAD

**Issue by chenjau** [RickStrahl/highlightjs-badge#1]
System: macOS 10.15.3
Chrome: 80.0.3987.122

works fine in safari && firefox. but not in chrome. 
after clicking the copy button, the clipboard is empty, and no errors in the console.

**Comment by RickStrahl** [comment]
Did you figure out what the problem was. Sorry missed this issue when it came through.

If it doesn't work can you try going to this page here and see if it's working?

https://weblog.west-wind.com/posts/2019/Dec/30/A-HighlightJs-Copy-Code-Badge-Component#single-line-code

and click on the copy links there? 

A few things to check are: Make sure you don't have copy disabled in your Chrome options.

**Comment by chenjau** [comment]
Hi! It's working now, but I don't know why(lots of code has been rewritten, conflict maybe?)
🤝
